services:
  - type: web
    name: sistema-igl-credenciados
    runtime: node
    plan: free
    nodeVersion: "18"
    buildCommand: npm install && cd client && npm install && CI=false npm run build
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: DRIVE_FOLDER_ID
        sync: false
      - key: JWT_SECRET
        generateValue: true
